import { Injectable } from '@nestjs/common';
import { DatabaseService } from '../db/database.service';
import { employees } from '../db/tables';
import { eq, count } from 'drizzle-orm';
import { CreateEmployeeDto } from './dto/create-employee.dto';
import { UpdateEmployeeDto } from './dto/update-employee.dto';
import { PaginationQuery } from '../types/pagination.types';
import { PaginationService } from '../services/pagination.service';
import { ResourceLinksService } from '../services/resource-links.service';

@Injectable()
export class EmployeesService {
  constructor(
    private readonly databaseService: DatabaseService,
    private readonly paginationService: PaginationService,
    private readonly resourceLinksService: ResourceLinksService,
  ) {}

  async findAll(pagination?: PaginationQuery) {
    const db = this.databaseService.getDatabase();

    const page = pagination?.page ?? 1;
    const limit = pagination?.limit ?? 10;
    const offset = (page - 1) * limit;

    const [{ total }] = await db.select({ total: count() }).from(employees);

    const rawData = await db.query.employees.findMany({
      limit,
      offset,
    });

    // Return raw data - links will be generated by interceptor
    const meta = this.paginationService.generateMeta(total, page, limit);

    return {
      data: rawData,
      meta,
    };
  }

  async findOne(id: string) {
    const db = this.databaseService.getDatabase();
    const employee = await db.query.employees.findFirst({
      where: eq(employees.id, id),
    });

    if (!employee) {
      return null;
    }

    // Return raw data - links will be generated by interceptor
    return { data: employee };
  }

  async create(createEmployeeDto: CreateEmployeeDto) {
    const db = this.databaseService.getDatabase();
    const [newEmployee] = await db.insert(employees).values(createEmployeeDto).returning();
    
    // Return raw data - links will be generated by interceptor
    return { data: newEmployee };
  }

  async update(id: string, updateEmployeeDto: UpdateEmployeeDto) {
    // TODO: Implement update functionality
    return `This action updates a #${id} employee`;
  }

  async remove(id: string) {
    const db = this.databaseService.getDatabase();
    await db.delete(employees).where(eq(employees.id, id));
  }
}
